Squashed 'externals/fmt/' changes from 3e75ad98..9e554999
9e554999 Update version
b34d92b0 Bump version
d39ece18 Make rst2md runnable and update changelog
fe2d715f Update changelog
27b30670 Update changelog
68837079 Update changelog
c98b202e Update changelog
587a7f66 Update changelog and docs
84e5170c Update changelog and deprecate visit
130e412b Update changelog and docs
0bbdca5b Fix conversion warnings (#989)
77a72448 Implement fill/align/width for strftime-like formatting
3e01376e Implement fill/align/width parsing in chrono formatter
1f92f8a9 Remove noexcept
8668639a Get rid of null_terminating_iterator in format
93fd473b Add support for builtin terminal colors. (#974)
61ad543c Windows .sln filename changed from FORMAT to FMT
7f7504b3 Clean up docs
37f599b1 Fix docs
8c2e15ae Make printf work in search (#164)
de71db6d Fix asan error (#977)
b180b391 Fix default formatting
24594c74 Disable printing the reset escape code when no style modifiers where applied. (#973)
b0f22247 Implement default chrono formatting
74927607 Add file stream support for stylized text printing. (#967)
f54f3d0f Move chrono-specific code to a separate header
bf1f1c73 Fix time test
b6bc6ec2 Add default ctor and fix use of constexpr macros in text_style
acfa95d4 Workaround a bug in MSVC's strftime (#965)
628f8305 More chrono formatting
aa3b5aba Implement locale-specific minute formatting
639de217 Workaround more MSVC bugs
3242ddf7 Fix warnings
bd110404 Workaround a bug in MSVC
81b5c4a5 Add experimental emphasis support (#961)
7c4eb0fb Fix warnings in time.h
2d624218 Fix another warning
b3168099 Fix a warning
b10ccb83 Add rpclib to projects
0497875f Stop the orgy of casts
37dc495b Simplify MSVC workaround
2ff4996d Fix ambiguous complier error C2666 in vs2017.The '+' opeator may cause ambiguity.Avoid implicit conversion.
77656c67 Fix sign-conversion warnings reported by Clang7
ea5e4790 Fix formatting
86681c4b Update README.rst
e867768e Do not override user provided compile flag
0c7f5c3c Update README.rst
e7e2ab10 Make return type of basic_format_args::max_size() consistent.
29352af3 Update README.rst
68214bd9 More time formatting
bcf3fcd6 Clean up bit fiddling for argument packing
9dcf127f Workaround a bogus MSVC warning
b8b06e3e Fix conversion warnings in Grisu
322b2594 Implement more time specifiers
0835f1ba Use full paths for fmt.pc.in
a084495d Add Ceph to projects
fa1d4dbc Fix warnings
2b2cfdac Update docs
99744f8f Suppress unfixable warning
f5fe8492 Specialize formatter for chrono durations
a5a9805a First stub at the datetime format parser
645c76a9 Fix dummy warnings
fecb2d6f Eliminate msvc compiler warnings (#931)
64690d3a Add context_base::arg()
01640f44 Fully qualify dummy_int (#941)
e37d6a98 add make_printf_args and make_wprintf_args functions (#934)
982ee5c6 parse_context -> format_parse_context
b7b85485 thousands_sep -> thousands_sep_impl (#939)
00a8cc83 Fix formatting
33fbb3a7 Fix remaining linker errors.
bd612159 Disable fmt-impl-test in windows + shared lib.
702b3d16 Fix link error in windows with shared library.
9d4ef943 Install pdb files.
6c95fb35 Default Context to format_context
16b78ee6 fix incompatibilities with c++2a mode in clang
19e00887 More locale support
f2ee9881 Improve locale support
1385050e More formatter tests
03c1b110 Fix gcc 4.4 build
cc805c61 Test enabled formatters
e0157923 Disallow leading zeros in arg-id
34030dec Cleanup warning flags
6b26e3f2 Manifest & Gradle comment
d286c977 Update for Gradle build
d951f6df Get latest Gradle (ver. 4.10.2)
a23d5924 Fix check_format_string (#925)
36161284 Update docs
38f355d8 Revert "find sphinx-build before calling build.py"
324eac1a Make locales work with any character type
bdda4d60 Simplify compile-time strings
5ee1a4bc check for property 'mutable iterator' and SFINAE on it
2dea780f change type naming and fix sfinae bug
b98e8301 add non-char support for compile-time format check
ccd3e8bb Make is_constructible public (#918)
43731538 Update usage.rst
73cfd8f3 Fix colored print
ec384302 additional test for print with background color
0a96c032 Parameterize v*printf on string type (#920)
61e6d2e3 Fix core version of vformat_to
ea4010d7 Merge has_to_string_view into is_string
486fff59 Add sprintf_format instantiations and remove syntactic noise
1e3dcbba fix: 'format_to_n' compiles 'std::back_inserter' arguments
f0328f8e Use char_traits::length in string_view ctor (#914)
895fb984 Disallow gcc 4.4 failures
20c708bf Fix build on gcc 4.4
9d0c9c4b cmake: output share/fmt.pc
2d2326a7 Fix compilation with older gcc
1ec02723 Get rid of FMT_UNION
2c81c851 Adapt any string-like type to be used by {fmt} just like the standard string types already supported. The adaption is totally non-intrusive.
846c644e Workeround broken sprintf in MSVC
13d472bd Compute output size for grisu
b71d3fe7 Remove use_grisu
847abb6f Fix test
dda47c94 Merge min_digits and max_digits
29246221 Fix naming of basic_format_specs members
bda5f9a5 Replace grisu2_specs with core_format_specs
b1ca608b Remove unused empty_spec
e8efdef8 Avoid extra copy
98f1c1fe Remove unused code
50b18a3c Integrate Grisu
69929752 Implement Grisu rounding
4bb76ef0 Remove redundant definition of print
ddd7caf3 Fix locale-dependent formatting (#905)
10e03e69 use found python executable for launching sphinx-build
07200f44 find sphinx-build before calling build.py
08a65c22 Workaround broken constexpr in MSVC2017
167f8fe3 Fix a typo in api.rst
57983423 Remove signbit workaround
7bebb3e1 Clarify overload resolution in docs
939fbe55 Remove basic_fixed_buffer.
61f81a07 minor documentation corrections
f27defc6 Parameterize printf functions on the type of the format string.
6a685571 Make 'std::*::basic_string_view' a valid argument type for 'format_str' parameters.
87a0408c Fix ostream.h build
2b5acad4 Remove redundant size argument to write_padded
655ce533 is_format_string -> is_string
fea712ab Parameterize ostream functions on the type of the format string.
f16a118e Fix non-matching char types.
041bf83d Improve fmt::format readability
22990323 Document how to write a formatter for a type hierarchy
f5480635 visit -> visit_format_arg
cdf3fa08 Put related code together in fmt/core.h
38325248 Count width in code points (#628)
deb901b9 Parameterize core functions on the type of the format string.
0f98de30 Update docs
c797708f Workaround strlen being non-constexpr in ARM toolchain
49b4c1e9 Update docs
63a87beb Add to_string_view
4e0c3146 checked_format_args -> checked_args
c3538a1e Simplify variadic functions further
2d7d0835 Simplify variadic functions
3f4cfa6c Implement UTF-8 string support
f8027414 Impelement char8_t support
76a47d41 Cleanup the use of FMT_CHAR
267fdc7a Parameterize core functions on the type of the format string.
5bced124 Parameterize more functions on string type
674999c5 fix vs2017 warning fmt::v5::localtime 'not all control paths return a value'.
e4fea22d Make char8_t a strongly-typed enum
66992e90 Clarify that writing to memory_buffer appends (#877)
e864acfd Fix compilation with intel compilers (ICC/ICPC) v14.0
4cf21f58 constrain templated format_to on proper format string type.
d7f17613 Fix compilation on platforms with exotic double (#878)
e4ca37cc Parameterize format_to on string type (#880)
d66fa221 Reduce syntactic noise
48e6dcd0 Implement workarounds for gcc 4.4
0ea3221d Remove is_named_arg and add FMT_CHAR
73c53d78 Parameterize 'printf(rgb color, ...)' and 'vprint_rgb(rgb color, ...)' on the type of the format string.
d41be23a Simplify string_view detection
2def9e4c Remove FMT_DTOR_NOEXCEPT
ff6e46ed More cleanup
715f2b4c Remove require_wchar and internalize no_formatter_error
ec0cdc46 Workaround Windows slowness

git-subtree-dir: externals/fmt
git-subtree-split: 9e554999ce02cf86fcdfe74fe740c4fe3f5a56d5